[theme]
base="light"
primaryColor="#0a66c2"     # same as .NET --primary
backgroundColor="#f2f5f9"  # same as body bg
secondaryBackgroundColor="#ffffff"
textColor="#1f2937"
font="sans serif"

form_bht_url = "https://script.google.com/macros/s/AKfycbxcQWju7zho6BOb710bIKqxsD_1tZ7mnFvRJ-YLLrSkGzaD54WbbZgCsnoEzQ-8dMKE/exec"
form_dr_url = "https://script.google.com/macros/s/AKfycbxUBFzrOUlgYlwqeVqnTzT072rNFxfsKCJQBZZ7xb8IxRLATl8KyPcIgRlkEVviWawp/exec"
token = "dev"
bht_csv_url = "https://docs.google.com/spreadsheets/d/1SYlCYxERDcI-PaQggyTOPgw4Ll5JIHPhQhJcjnD5ih0/edit?gid=0#gid=0"
dr_csv_url = "https://docs.google.com/spreadsheets/d/1AMMfzbKreprRrhzJwMeQq9_2spdEvDLfGtEYnEMyF_8/edit?gid=0#gid=0"